### ISSUE TITLE
Increase active card contrast

### ISSUE THREAD

**Issue by alexander-bauer** [idiotic/idiotic-webui#30]
It's fairly hard to distinguish items that are on from items that are off.

**Comment by alexander-bauer** [comment]
@dylwhich The color of active/non-active items changed in 067b6a33869225c1ec3a2ae2d5c883c34fb58a0c, the first collapsible change. Do you think this is sufficient?

**Comment by dylwhich** [comment]
Yup, looks much more distinct now. I would call it good!

**Comment by alexander-bauer** [comment]
Closed in 067b6a33869225c1ec3a2ae2d5c883c34fb58a0c.
